services:
  uptime-kuma:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3003:3001"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
    mem_limit: 512m
